// cardData.js - Chance and Community Chest Cards
module.exports = {
  chance: [
    { id: 'c1', textAz: 'Başlanğıca get. 200₼ topla.', textEn: 'Advance to GO. Collect 200₼.', action: { type: 'move', target: 0, collectGo: true } },
    { id: 'c2', textAz: 'İçərişəhərə get.', textEn: 'Advance to Icherisheher.', action: { type: 'move', target: 39 } },
    { id: 'c3', textAz: 'Hava Limanına get.', textEn: 'Advance to Airport.', action: { type: 'move', target: 5, collectGo: true } },
    { id: 'c4', textAz: 'Ən yaxın transporta get. Sahibinə 2 qat icarə ödə.', textEn: 'Advance to nearest transport. Pay owner double rent.', action: { type: 'nearestTransport', doubleRent: true } },
    { id: 'c5', textAz: 'Bank dividend ödəyir. 50₼ al.', textEn: 'Bank pays dividend. Collect 50₼.', action: { type: 'collectFromBank', amount: 50 } },
    { id: 'c6', textAz: 'Həbsdən azad ol. Bu kartı saxla.', textEn: 'Get out of jail free. Keep this card.', action: { type: 'jailFree' } },
    { id: 'c7', textAz: '3 xana geriyə qayıt.', textEn: 'Go back 3 spaces.', action: { type: 'moveBack', spaces: 3 } },
    { id: 'c8', textAz: 'Həbsə get. Birbaşa həbsxanaya get.', textEn: 'Go to jail. Go directly to jail.', action: { type: 'jail' } },
    { id: 'c9', textAz: 'Küçə təmiri. Hər ev üçün 25₼, otel üçün 100₼ ödə.', textEn: 'Make repairs. Pay 25₼ per house, 100₼ per hotel.', action: { type: 'repairs', houseCost: 25, hotelCost: 100 } },
    { id: 'c10', textAz: 'Sürücülük cəriməsi - 15₼ ödə.', textEn: 'Speeding fine - pay 15₼.', action: { type: 'payBank', amount: 15 } },
    { id: 'c11', textAz: 'Dəmiryoluna get.', textEn: 'Advance to Railway Station.', action: { type: 'move', target: 15, collectGo: true } },
    { id: 'c12', textAz: 'Bank səhvi sizin xeyrinizə - 200₼ al.', textEn: 'Bank error in your favor. Collect 200₼.', action: { type: 'collectFromBank', amount: 200 } },
    { id: 'c13', textAz: 'İdman yarışmasında qalib oldunuz. Hər oyunçudan 50₼ al.', textEn: 'You won a sports competition. Collect 50₼ from each player.', action: { type: 'collectFromAll', amount: 50 } },
    { id: 'c14', textAz: 'Nizami küçəsinə get.', textEn: 'Advance to Nizami street.', action: { type: 'move', target: 31, collectGo: true } },
    { id: 'c15', textAz: 'Doğum günü - Hər oyunçu sizə 10₼ verir.', textEn: 'Birthday! Collect 10₼ from each player.', action: { type: 'collectFromAll', amount: 10 } },
    { id: 'c16', textAz: 'Vergi geri qaytarıldı. 20₼ al.', textEn: 'Tax refund. Collect 20₼.', action: { type: 'collectFromBank', amount: 20 } },
  ],
  community: [
    { id: 'cc1', textAz: 'Bank xətası. Sizin xeyrinizə - 200₼ al.', textEn: 'Bank error. Collect 200₼.', action: { type: 'collectFromBank', amount: 200 } },
    { id: 'cc2', textAz: 'Həkim haqqı - 50₼ ödə.', textEn: 'Doctor\'s fee - pay 50₼.', action: { type: 'payBank', amount: 50 } },
    { id: 'cc3', textAz: 'Satış komissionu - 25₼ al.', textEn: 'Sale commission. Collect 25₼.', action: { type: 'collectFromBank', amount: 25 } },
    { id: 'cc4', textAz: 'Ömür sığortası ödənişi - 100₼ al.', textEn: 'Life insurance matures. Collect 100₼.', action: { type: 'collectFromBank', amount: 100 } },
    { id: 'cc5', textAz: 'Həbsdən azad ol. Bu kartı saxla.', textEn: 'Get out of jail free. Keep this card.', action: { type: 'jailFree' } },
    { id: 'cc6', textAz: 'Həbsə get. Birbaşa həbsxanaya get.', textEn: 'Go to jail. Go directly to jail.', action: { type: 'jail' } },
    { id: 'cc7', textAz: 'Konsert bileti gəliri - 50₼ al.', textEn: 'Concert ticket income. Collect 50₼.', action: { type: 'collectFromBank', amount: 50 } },
    { id: 'cc8', textAz: 'Miras - 100₼ al.', textEn: 'Inheritance. Collect 100₼.', action: { type: 'collectFromBank', amount: 100 } },
    { id: 'cc9', textAz: 'Xəstəxana haqqı - 100₼ ödə.', textEn: 'Hospital fees. Pay 100₼.', action: { type: 'payBank', amount: 100 } },
    { id: 'cc10', textAz: 'Məktəb haqqı - 150₼ ödə.', textEn: 'School fees. Pay 150₼.', action: { type: 'payBank', amount: 150 } },
    { id: 'cc11', textAz: 'Xidmət mükafatı - 20₼ al.', textEn: 'Service award. Collect 20₼.', action: { type: 'collectFromBank', amount: 20 } },
    { id: 'cc12', textAz: 'Müsabiqədə 2-ci oldunuz. Hər oyunçuya 10₼ verin.', textEn: 'You came 2nd in beauty contest. Pay each player 10₼.', action: { type: 'payAll', amount: 10 } },
    { id: 'cc13', textAz: 'Doğum günü. Hər oyunçudan 10₼ al.', textEn: 'Birthday. Collect 10₼ from each player.', action: { type: 'collectFromAll', amount: 10 } },
    { id: 'cc14', textAz: 'Vergi geri qaytarıldı - 20₼ al.', textEn: 'Tax refund. Collect 20₼.', action: { type: 'collectFromBank', amount: 20 } },
    { id: 'cc15', textAz: 'Başlanğıca get. 200₼ topla.', textEn: 'Advance to GO. Collect 200₼.', action: { type: 'move', target: 0, collectGo: true } },
    { id: 'cc16', textAz: 'Ev təmiri. Hər ev üçün 40₼, otel üçün 115₼ ödə.', textEn: 'Home repairs. Pay 40₼ per house, 115₼ per hotel.', action: { type: 'repairs', houseCost: 40, hotelCost: 115 } },
  ]
};
